version: 0.2
phases:
  install:
    runtime-versions:
        docker: 18
    pre_build:
    commands:
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin <ECR URL>.amazonaws.com
  build:
    commands:
      - echo Building the Docker image ... | tee -a log.txt
      - docker build -t <ECR URL>.amazonaws.com/backend:latest . 2>&1 | tee -a log.txt
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push <ECR URL>.amazonaws.com/backend:latest
