version: "3.7"

volumes:
  database:
  redis:


services:
  backend:
    build: .
    restart: 'on-failure'
    command: bash docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - FLASK_APP=main:app
      - DATABASE_URL=guts-postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
  

  postgres:
    image: postgres:12-alpine
    container_name: 'guts-postgres'
    restart: 'no'
    volumes:
      - database:/var/lib/postgresql/data:z
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
